version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 10
    commands:
      - echo "installing something"
  pre_build:
    commands:
      - echo "we are in the pre build phase"
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - grep -Fq "HEJHEJ" index.html
  post_build:
    commands:
      - echo "we are in the post build phase"
